<?php


/*
Plugin Name: wp_useful_comments.
Plugin URI: http://www.ll19.com/?p=126
Description: Set useful comments for post each. Upload `useful_comments` to the `/wp-content/plugins/` directory, To show useful comments put <code>&lt;?php wp_uc_flash(); ?></code> in your templates~ Navigate to `Editing Comment` page to configure or cancel useful comments.
Version: 2.0
Author: LL19.com
Author URI: http://www.ll19.com/
*/

if (!isset ($wpdb)) {
	wp_useful_comments_init();
}

$ucTextDomain = 'UsefulComments';
$ucUrlDomain = "";
if (@ file_exists(TEMPLATEPATH . '/useful_comments.php')) {
	$ucUrlDomain = get_stylesheet_directory_uri() . "/";
} else {
	$ucUrlDomain = WP_PLUGIN_URL . "/useful_comments/";
}

class wp_useful_comments {
	function install() {
		global $wpdb;
		$result = mysql_query("CREATE TABLE `$wpdb->useful_comments`(`commentid` INT( 20 ) NOT NULL ,`postid` INT( 20 ) NOT NULL ,PRIMARY KEY ( `commentid` ))", $wpdb->dbh) or die(mysql_error() . ' on line: ' . __LINE__);
		if (!$result) {
			return false;
		}
		return true;
	}
}

/*
creat table wp_useful_comments.
*/
function wp_useful_comments_init() {
	global $wpdb, $wp_uc;

	$wpdb->useful_comments = $wpdb->prefix . 'useful_comments';
	$wp_uc = new wp_useful_comments;
	$result = mysql_list_tables(DB_NAME);
	$tables = array ();
	while ($row = mysql_fetch_row($result)) {
		$tables[] = $row[0];
	}
	if (!in_array($wpdb->useful_comments, $tables)) {
		$wp_uc->install();
	}
}

add_action('admin_print_scripts', 'uc_tag_js_header');
function uc_tag_js_header() {
	global $ucUrlDomain;
	// use JQuery
	echo "\n" . '<!-- Start Of Script Generated By wp_useful_comments 1.0  Author: LL19.com -->' . "\n";
	wp_print_scripts('jquery');
	echo '<script src="' . $ucUrlDomain . 'uc.js" type="text/javascript"></script>' . "\n";
	echo '<!-- End Of Script Generated By wp_useful_comments 1.0  Author: LL19.com -->' . "\n";
}

function uc_edit_text_form() {
	global $ucTextDomain, $ucUrlDomain, $comment, $wpdb, $table_prefix;
	$query = "SELECT * FROM " . $table_prefix . "useful_comments WHERE commentid = '" . $comment->comment_ID . "'";
	$wp_select_uc_callback = $wpdb->query($query);
	if ($wp_select_uc_callback == 0) {
		echo '<div id="previewview" name="uc_button"><a href="javascript:ucAjaxDB(\'insert\');" id="uc_19_set_button">' . __("Useful Comment", $ucTextDomain) . '</a></div>';
	} else {
		echo '<div id="previewview" name="uc_button"><a href="javascript:ucAjaxDB(\'delete\');" id="uc_19_set_button">' . __("Cancel Useful Comment", $ucTextDomain) . '</a></div>';
	}
?>
<script type="text/javascript">
function ucAjaxDB(action) {
   jQuery(document).ready(function() {     
   var cid = (jQuery("input[name='comment_ID']").val());
   var pid = (jQuery("input[name='comment_post_ID']").val());
   var set = {c:cid,p:pid,u:"<?php echo $ucUrlDomain;?>useful_comments_db.php",ucaction:action};
   if(cid == null || pid == null ){
		alert ("Error! comment_ID or comment_post_ID is null!")
		return false;
   } else {
   wp_uc_ajax_db(set);
   }
   });
}
</script>
<?php


}

function add_uc_edit_text_form(){
    add_meta_box('uc_edit_text_form_id', 'UC comment', 'uc_edit_text_form', 'comment', 'normal', 'high');
}
add_action('admin_menu', 'add_uc_edit_text_form');


/*
add flash
*/
function wp_uc_flash() {
	global $ucUrlDomain, $wpdb;
	$sqlcount = "SELECT count(*) FROM `wp_useful_comments` WHERE `postid` = '" . get_the_ID() . "'";
	$uc_count = $wpdb->get_var($sqlcount);
	if ($uc_count > 0) {
?>

<div class="uc_flash">
  <object type="application/x-shockwave-flash" data="<?php echo $ucUrlDomain;?>LL19.com.swf?p=<?php the_ID() ?>" width="100%" height="100%">
    <param name="wmode" value="transparent" />
    <param name="movie" value="<?php echo $ucUrlDomain;?>LL19.com.swf?p=<?php the_ID() ?>" />
  </object>
</div>
<?php

	}
}

/*
add admin page
*/
add_action('admin_menu', 'wp_uc_admin_page');
function wp_uc_admin_page() {
	if (function_exists('add_options_page')) {
		add_options_page(__('UC Admin Page', 'uc_admin_page'), __('UC Admin Page', 'uc_admin_page'), 8, basename(__FILE__), 'wp_uc_admin_page_form');
	}
}
function wp_uc_admin_page_form() {
	global $ucUrlDomain;
?>
<div style="padding:50px;">
  <h2>
    <script type="text/javascript">
	var tmp="\u5982\u679c\u4f60\u5220\u9664\u4e86\u5df2\u7ecf\u8bbe\u7f6e\u4e3a\u6709\u7528\u7559\u8a00\u7684\u7559\u8a00\u4e0d\u8fc7\u5220\u9664\u524d\u672a\u53d6\u6d88\u6b64\u6709\u7528\u7559\u8a00\uff0c\u53ef\u4ee5\u70b9\u51fb\u4e0b\u9762\u7684\u6309\u94ae\u6e05\u9664UC\u8868\u7684\u65e0\u7528\u4fe1\u606f\u3002";
	document.writeln(tmp);
	</script>
  </h2>
  <div id="uc_call_back" style="display:none; margin: 20px;"></div>
  <form action="<?php echo $uc_delete_form;?>" method="post" id="uc_delete">
    <input type="button" value="Click This Button." id="uc_delete_button"/>
  </form>
  <script type="text/javascript">
	jQuery('#uc_delete_button').click(function() {
		jQuery.ajax({
		url : "<?php echo $ucUrlDomain;?>useful_comments_db.php",
		dataType : "html",
		type : "post",
		data : "ucaction=delete_uc",
		success : function(msg) {
			jQuery("#uc_call_back").html(msg);
			jQuery("#uc_call_back").slideDown(); 
		},
		error : function(msg) {
			jQuery("#uc_call_back").html(msg);
			jQuery("#uc_call_back").slideDown(); 
		}
		})
	})
	</script>
</div>
<?php

}
?>
